<?php

return [
    'languages' => [
//        "af" => ["direction" => "ltr", "regional" => "af_ZA", "name" => "Afrikaans", "native" => "Afrikaans"],
//        "ak" => ["direction" => "ltr", "regional" => "ak_GH", "name" => "Akan", "native" => "Akan"],
//        "sq" => ["direction" => "ltr", "regional" => "sq_AL", "name" => "Albanian", "native" => "Shqip"],
//        "am" => ["direction" => "ltr", "regional" => "am_ET", "name" => "Amharic", "native" => "አማርኛ"],
//        "ar" => ["direction" => "rtl", "regional" => "ar_AE", "name" => "Arabic", "native" => "العربية"],
//        "hy" => ["direction" => "ltr", "regional" => "hy_AM", "name" => "Armenian", "native" => "Հայերեն"],
//        "as" => ["direction" => "ltr", "regional" => "as_IN", "name" => "Assamese", "native" => "অসমীয়া"],
//        "az" => ["direction" => "ltr", "regional" => "az_AZ", "name" => "Azerbaijani", "native" => "azərbaycan dili, تۆرکجه"],
//        "bm" => ["direction" => "ltr", "regional" => "bm_ML", "name" => "Bambara", "native" => "bamanankan"],
//        "eu" => ["direction" => "ltr", "regional" => "eu_ES", "name" => "Basque", "native" => "euskara, euskera"],
//        "be" => ["direction" => "ltr", "regional" => "be_BY", "name" => "Belarusian", "native" => "беларуская мова"],
//        "bs" => ["direction" => "ltr", "regional" => "bs_BA", "name" => "Bosnian", "native" => "bosanski jezik"],
//        "br" => ["direction" => "ltr", "regional" => "br_FR", "name" => "Breton", "native" => "brezhoneg"],
//        "bg" => ["direction" => "ltr", "regional" => "bg_BG", "name" => "Bulgarian", "native" => "български език"],
//        "my" => ["direction" => "ltr", "regional" => "my_MM", "name" => "Burmese", "native" => "ဗမာစာ"],
//        "ce" => ["direction" => "ltr", "regional" => "ce_RU", "name" => "Chechen", "native" => "нохчийн мотт"],
//        "zh" => ["direction" => "ltr", "regional" => "zh_CN", "name" => "Chinese", "native" => "简体中文"],
//        "zh-Hant" => ["direction" => "ltr", "regional" => "zh_CN", "name" => "Chinese", "native" => "繁體中文"],
//        "kw" => ["direction" => "ltr", "regional" => "kw_GB", "name" => "Cornish", "native" => "Kernewek"],
//        "hr" => ["direction" => "ltr", "regional" => "hr_HR", "name" => "Croatian", "native" => "Hrvatski"],
//        "cs" => ["direction" => "ltr", "regional" => "cs_CZ", "name" => "Czech", "native" => "čeština, český jazyk"],
//        "da" => ["direction" => "ltr", "regional" => "da_DK", "name" => "Danish", "native" => "Dansk"],
//        "dz" => ["direction" => "ltr", "regional" => "dz_BT", "name" => "Dzongkha", "native" => "རྫོང་ཁ"],
        "en" => ["direction" => "ltr", "regional" => "en_GB", "name" => "English", "native" => "English"],
//        "en-CA" => ["direction" => "ltr", "regional" => "en_CA", "name" => "Canadian English", "native" => "English"],
//        "en-GB" => ["direction" => "ltr", "regional" => "en_GB", "name" => "British English", "native" => "British English"],
//        "en-US" => ["direction" => "ltr", "regional" => "en_US", "name" => "U.S. English", "native" => "U.S. English"],
//        "et" => ["direction" => "ltr", "regional" => "et_EE", "name" => "Estonian", "native" => "eesti, eesti keel"],
//        "ee" => ["direction" => "ltr", "regional" => "ee_GH", "name" => "Ewe", "native" => "Eʋegbe"],
//        "fo" => ["direction" => "ltr", "regional" => "fo_DK", "name" => "Faroese", "native" => "føroyskt"],
//        "fi" => ["direction" => "ltr", "regional" => "fi_FI", "name" => "Finnish", "native" => "Suomi"],
//        "fr" => ["direction" => "ltr", "regional" => "fr_FR", "name" => "French", "native" => "Français"],
//        "fr-CA" => ["direction" => "ltr", "regional" => "fr-CA", "name" => "Canadian French", "native" => "français canadien"],
//        "ff" => ["direction" => "ltr", "regional" => "ff_CM", "name" => "Fulah", "native" => "Fulfulde, Pulaar, Pular"],
//        "gl" => ["direction" => "ltr", "regional" => "gl_ES", "name" => "Galician", "native" => "Galego"],
//        "ka" => ["direction" => "ltr", "regional" => "ka_GE", "name" => "Georgian", "native" => "ქართული"],
        "de" => ["direction" => "ltr", "regional" => "de_DE", "name" => "German", "native" => "Deutsch"],
//        "de-AT" => ["direction" => "ltr", "regional" => "de_AT", "name" => "Austrian German", "native" => "Österreichisches Deutsch"],
//        "gu" => ["direction" => "ltr", "regional" => "gu_IN", "name" => "Gujarati", "native" => "ગુજરાતી"],
//        "ha" => ["direction" => "rtl", "regional" => "ha_GH", "name" => "Hausa", "native" => "(Hausa) هَوُسَ"],
//        "he" => ["direction" => "rtl", "regional" => "he_IL", "name" => "Hebrew", "native" => "עברית"],
//        "hi" => ["direction" => "ltr", "regional" => "hi_IN", "name" => "Hindi", "native" => "हिन्दी, हिंदी"],
//        "hu" => ["direction" => "ltr", "regional" => "hu_HU", "name" => "Hungarian", "native" => "Magyar"],
//        "id" => ["direction" => "ltr", "regional" => "id_ID", "name" => "Indonesian", "native" => "Bahasa Indonesia"],
//        "ga" => ["direction" => "ltr", "regional" => "ga_IE", "name" => "Irish", "native" => "Gaeilge"],
//        "ig" => ["direction" => "ltr", "regional" => "ig_NG", "name" => "Igbo", "native" => "Asụsụ Igbo"],
//        "is" => ["direction" => "ltr", "regional" => "is_IS", "name" => "Icelandic", "native" => "Íslenska"],
//        "it" => ["direction" => "ltr", "regional" => "it_IT", "name" => "Italian", "native" => "Italiano"],
//        "ja" => ["direction" => "ltr", "regional" => "ja_JP", "name" => "Japanese", "native" => "日本語 (にほんご)"],
//        "kn" => ["direction" => "ltr", "regional" => "kn_IN", "name" => "Kannada", "native" => "ಕನ್ನಡ"],
//        "ks" => ["direction" => "rtl", "regional" => "ks_IN", "name" => "Kashmiri", "native" => "कश्मीरी, كشميري‎"],
//        "kk" => ["direction" => "ltr", "regional" => "kk_KZ", "name" => "Kazakh", "native" => "қазақ тілі"],
//        "rw" => ["direction" => "ltr", "regional" => "rw_RW", "name" => "Kinyarwanda", "native" => "Ikinyarwanda"],
//        "ko" => ["direction" => "ltr", "regional" => "ko_KR", "name" => "Korean", "native" => "한국어"],
//        "lg" => ["direction" => "ltr", "regional" => "lg_UG", "name" => "Ganda", "native" => "Luganda"],
//        "ln" => ["direction" => "ltr", "regional" => "ln_AO", "name" => "Lingala", "native" => "Lingála"],
//        "lo" => ["direction" => "ltr", "regional" => "lo_LA", "name" => "Lao", "native" => "ພາສາລາວ"],
//        "lt" => ["direction" => "ltr", "regional" => "lt_LT", "name" => "Lithuanian", "native" => "lietuvių kalba"],
//        "lv" => ["direction" => "ltr", "regional" => "lv_LV", "name" => "Latvian", "native" => "latviešu valoda"],
//        "gv" => ["direction" => "ltr", "regional" => "gv_IM", "name" => "Manx", "native" => "Gaelg, Gailck"],
//        "mk" => ["direction" => "ltr", "regional" => "mk_MK", "name" => "Macedonian", "native" => "македонски јазик"],
//        "mg" => ["direction" => "ltr", "regional" => "mg_MG", "name" => "Malagasy", "native" => "fiteny malagasy"],
//        "ms" => ["direction" => "ltr", "regional" => "ms_MY", "name" => "Malay", "native" => "Bahasa Melayu"],
//        "ml" => ["direction" => "ltr", "regional" => "ml_IN", "name" => "Malayalam", "native" => "മലയാളം"],
//        "mt" => ["direction" => "ltr", "regional" => "mt_MT", "name" => "Maltese", "native" => "Malti"],
//        "mr" => ["direction" => "ltr", "regional" => "mr_IN", "name" => "Marathi", "native" => "मराठी"],
//        "mn" => ["direction" => "ltr", "regional" => "mn_MN", "name" => "Mongolian", "native" => "Монгол хэл"],
//        "nd" => ["direction" => "ltr", "regional" => "nd_ZW", "name" => "North Ndebele", "native" => "isiNdebele"],
//        "ne" => ["direction" => "ltr", "regional" => "ne_IN", "name" => "Nepali", "native" => "नेपाली"],
//        "om" => ["direction" => "ltr", "regional" => "om_ET", "name" => "Oromo", "native" => "Oromoo"],
//        "fa" => ["direction" => "rtl", "regional" => "fa_IR", "name" => "Persian", "native" => "فارسی"],
//        "pl" => ["direction" => "ltr", "regional" => "pl_PL", "name" => "Polish", "native" => "Polski"],
//        "pt" => ["direction" => "ltr", "regional" => "pt_PT", "name" => "Portuguese", "native" => "Português"],
//        "pt-BR" => ["direction" => "ltr", "regional" => "pt_BR", "name" => "Brazilian Portuguese", "native" => "português do Brasil"],
//        "qu" => ["direction" => "ltr", "regional" => "qu_BO", "name" => "Quechua", "native" => "Runa Simi, Kichwa"],
//        "rm" => ["direction" => "ltr", "regional" => "rm_CH", "name" => "Romansh", "native" => "Rumantsch Grischun"],
//        "rn" => ["direction" => "ltr", "regional" => "rn_BI", "name" => "Rundi", "native" => "Ikirundi"],
//        "ru" => ["direction" => "ltr", "regional" => "ru_RU", "name" => "Russian", "native" => "русский"],
//        "se" => ["direction" => "ltr", "regional" => "se_FI", "name" => "Northern Sami", "native" => "Davvisámegiella"],
//        "sg" => ["direction" => "ltr", "regional" => "sg_CF", "name" => "Sango", "native" => "Sängö"],
//        "sr" => ["direction" => "ltr", "regional" => "sr_RS", "name" => "Serbian", "native" => "Српски"],
//        "sn" => ["direction" => "ltr", "regional" => "sn_ZW", "name" => "Shona", "native" => "chiShona"],
//        "sk" => ["direction" => "ltr", "regional" => "sk_SK", "name" => "Slovak", "native" => "slovenčina"],
//        "sl" => ["direction" => "ltr", "regional" => "sl_SI", "name" => "Slovene", "native" => "slovenščina"],
//        "so" => ["direction" => "ltr", "regional" => "so_DJ", "name" => "Somali", "native" => "Soomaali"],
//        "sw" => ["direction" => "ltr", "regional" => "sw_CD", "name" => "Swahili", "native" => "Kiswahili"],
//        "sv" => ["direction" => "ltr", "regional" => "sv_SE", "name" => "Swedish", "native" => "Svenska"],
//        "ta" => ["direction" => "ltr", "regional" => "ta_IN", "name" => "Tamil", "native" => "தமிழ்"],
//        "te" => ["direction" => "ltr", "regional" => "te_IN", "name" => "Telugu", "native" => "తెలుగు"],
//        "tg" => ["direction" => "ltr", "regional" => "tg_TJ", "name" => "Tajik", "native" => "тоҷикӣ"],
//        "th" => ["direction" => "ltr", "regional" => "th_TH", "name" => "Thai", "native" => "ไทย"],
//        "ti" => ["direction" => "ltr", "regional" => "ti_ER", "name" => "Tigrinya", "native" => "ትግርኛ"],
//        "bo" => ["direction" => "ltr", "regional" => "bo_CN", "name" => "Tibetan", "native" => "བོད་ཡིག"],
//        "tr" => ["direction" => "ltr", "regional" => "tr_TR", "name" => "Turkish", "native" => "Türkçe"],
//        "tt" => ["direction" => "ltr", "regional" => "tt_RU", "name" => "Tatar", "native" => "татар теле"],
//        "uk" => ["direction" => "ltr", "regional" => "uk_UA", "name" => "Ukrainian", "native" => "Українська"],
//        "ur" => ["direction" => "rtl", "regional" => "ur_PK", "name" => "Urdu", "native" => "اردو"],
//        "vi" => ["direction" => "ltr", "regional" => "vi_VN", "name" => "Vietnamese", "native" => "Tiếng Việt"],
//        "cy" => ["direction" => "ltr", "regional" => "cy_GB", "name" => "Welsh", "native" => "Cymraeg"],
//        "wo" => ["direction" => "ltr", "regional" => "wo_SN", "name" => "Wolof", "native" => "Wollof"],
//        "fy" => ["direction" => "ltr", "regional" => "fy_NL", "name" => "Western Frisian", "native" => "Frysk"],
//        "yi" => ["direction" => "rtl", "regional" => "yi_001", "name" => "Yiddish", "native" => "ייִדיש"],
//        "yo" => ["direction" => "ltr", "regional" => "yo_BJ", "name" => "Yoruba", "native" => "Yorùbá"],
//        "zu" => ["direction" => "ltr", "regional" => "zu_ZA", "name" => "Zulu", "native" => "isiZulu"],
//        "ro" => ["direction" => "ltr", "regional" => "ro_RO", "name" => "Romanian", "native" => "Română"],
//        "es" => ["direction" => "ltr", "regional" => "es_ES", "name" => "Spanish", "native" => "Español"],
//        "nl" => ["direction" => "ltr", "regional" => "nl_NL", "name" => "Dutch", "native" => "Nederlands"],
    ]
];
